# Generated by Django 4.2.7 on 2023-11-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lineas_investigacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='iconos/', verbose_name='imagen')),
                ('descripccion', models.TextField(max_length=250, null=True, verbose_name='Descripción')),
            ],
        ),
    ]
